### ISSUE TITLE
[aur/wechat] 图标上的"Toggle Sandbox"不能启用沙盒

### ISSUE THREAD

**Issue by njpig** [Kraftland/portable#11]
1. ArchLinux更新到最新（2024.11.25)
2. wechat 4.0.0.23-12(https://aur.archlinux.org/packages/wechat)

升级到wechat 4.0.0.23-12之前并没有启动沙盒，升级wechat 4.0.0.23-12之后，点击"Toggle Sandbox"不能启用沙盒。

需要手动修改 ~/.local/share/WeChat_Data/options/sandbox，把disableSandbox改成enableSandbox后，就能启用沙盒。

**Comment by Kimiblock** [comment]
KDE Wayland 虚拟机测试并无问题. 尝试更新到最新版 `portable-git`
