### ISSUE TITLE
portable can't set enviroment variable properly

### ISSUE THREAD

**Issue by MareDevi** [Kraftland/portable#26]
in the protable config it has setted `QT_SCALE_FACTOR=1.5 ` but it didn't work
use `systemctl --user set-environment QT_SCALE_FACTOR=1.5` it works.

**Comment by MareDevi** [comment]
> portable-git

It works! thx

**Comment by Kimiblock** [comment]
> It works! thx

Okay, RC is out and stable release is coming in this week
